dinnerorder/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('order_app.urls')),
    url(r'^admin/', admin.site.urls),
]

order_app/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.user, name='user'),
    url(r'^orders', views.ordertable, name='ordertable'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^order/(?P<pk>[0-9]+)/delete/$', views.delete, name='delete'),
    url(r'^order/(?P<pk>[0-9]+)/edit/$', views.edit, name='edit'),
]

order_app/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class DUserModel(models.Model):
    item = models.CharField(max_length=100)
    whom = models.CharField(max_length=100, blank=True)
    e_mail = models.EmailField(blank=True)
    byr = models.IntegerField(blank=True, null=True)
    byn = models.FloatField(null=True, blank=True)
    comment = models.CharField(max_length=200, blank=True, null=True)

    def __unicode__(self):
        return self.item

order_app/forms.py
from models import DUserModel
from django import forms


class DUserForm(forms.ModelForm):
    class Meta:
        model = DUserModel
        fields = '__all__'

order_app/views.py
import exceptions
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
import forms
import datetime
import models
from django.contrib.auth.decorators import login_required
from utils import send_mail_to_user, send_mail_to_admin, cur_hour
import copy

# Create your views here.


def user(request):

    if request.method == 'POST':
        form = forms.DUserForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            item=data['item']
            whom=data['whom']
            e_mail=data['e_mail']
            byr=data['byr']
            byn=data['byn']
            comment=data['comment']
            models.DUserModel.objects.create(item=item, whom=whom, e_mail=e_mail, byr=byr, byn=byn, comment=comment)
            send_mail_to_admin(whom=whom, item=item, mail=e_mail)
            return render(request, 'confirmation.html', {'message': 'Your order %s is processing' % item})
        else:
            return render(request, 'duserform.html', {'form':form})

    else:
        if 13 <= cur_hour() <= 15:
            status = True
        else:
            status = False
        # status = True  # zaplatka
        return render(request, 'duserform.html', {'form': forms.DUserForm(), 'status': status})


@login_required
def ordertable(request):
    orders = models.DUserModel.objects.all()
    summ_in_byr = 0
    summ_in_byn = 0
    itog = 0
    for order in orders:
        if order.byn is None:
            order.byn = 0
        elif order.byr is None:
            order.byr = 0
        summ_in_byn += float(order.byn)
        summ_in_byr += int(order.byr)
    itog = summ_in_byn + summ_in_byr / 10000.0
    return render(request, 'orderstable.html', {'orders': orders, 'byn': summ_in_byn, 'byr': summ_in_byr, 'itog': itog})


@login_required(login_url='/accounts/login/')
def edit(request, pk):
    if request.method == 'POST':
        form=forms.DUserForm(request.POST)
        if form.is_valid():
            data=form.cleaned_data
            my_object = models.DUserModel.objects.get(pk=pk)
            my_old_object = copy.copy(my_object)
            my_object.item = data['item']
            my_object.whom = data['whom']
            my_object.e_mail = data['e_mail']
            my_object.byn = data['byn']
            my_object.byr = data['byr']
            my_object.comment = data['comment']
            my_object.save()
            if my_old_object.comment != my_object.comment or my_old_object.item != my_object.item:
                send_mail_to_user(mail=my_object.e_mail, item=my_object.item, comment=my_object.comment)
            return redirect('ordertable')
        else:
            my_object = forms.DUserForm.objects.get(pk=pk)
            return render(request, 'editform.html', {'form':forms.DUserForm(initial={
                'item': my_object.item,
                'whom': my_object.whom,
                'e_mail':my_object.e_mail,
                'byr':my_object.byr,
                'byn':my_object.byn,
                'comment':my_object.comment,
            }), 'pk': pk})

    else:
        my_object = models.DUserModel.objects.get(pk=pk)
        return render(request, 'editform.html', {'form': forms.DUserForm(initial={
            'item': my_object.item,
                'whom': my_object.whom,
                'e_mail':my_object.e_mail,
                'byr':my_object.byr,
                'byn':my_object.byn,
                'comment':my_object.comment
            }), 'pk': pk})


@login_required(login_url='/accounts/login/')
def delete(request, pk):
    try:
        my_object = models.DUserModel.objects.get(pk=pk)
        email = my_object.e_mail
        my_object.delete()
        send_mail_to_user(mail=email, item=None, comment=None)
    except ObjectDoesNotExist:
        return redirect('ordertable')
    return redirect('ordertable')

order_app/templates/base.html
{% load staticfiles %}
<html>
<head>

<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>{% block title %}{% endblock %}</title>

</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

order_app/templates/confirmation.html
{{ message }}

order_app/templates/duserform.html
{% block content %}
<form method="post" action="{% url 'user' %}">
    {% csrf_token %}
    {% if status %}
    {{ form.as_p }}
    <p><input type="submit" value="OK"></p>
    {% else %}
        <a><h2>Your order can't be done!</h2></a>
    <td>
        <p><tr><th><label for="id_item">Item:</label></th><td><input id="id_item" maxlength="100" name="item" type="text" disabled/></td></tr></p>
        <p><tr><th><label for="id_whom">Whom:</label></th><td><input id="id_whom" maxlength="100" name="whom" type="text" disabled/></td></tr></p>
        <p><tr><th><label for="id_e_mail">E mail:</label></th><td><input id="id_e_mail" maxlength="254" name="e_mail" type="email" disabled/></td></tr></p>
        <p><tr><th><label for="id_byr">Byr:</label></th><td><input id="id_byr" name="byr" type="number" disabled/></td></tr></p>
        <p><tr><th><label for="id_byn">Byn:</label></th><td><input id="id_byn" name="byn" step="any" type="number" disabled/></td></tr></p>
        <p><tr><th><label for="id_comment">Comment:</label></th><td><input id="id_comment" maxlength="200" name="comment" type="text" disabled/></td></tr></p>
    </td>
        <p><input type="submit" value="OK" disabled></p>
    {% endif %}

</form>
{% endblock %}

order_app/templates/editform.html
<form method="post" action="{% url 'edit' pk%}">
    {% csrf_token %}
    {{ form.as_p }}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<p><input type="submit" value="OK"></p>
</form>

order_app/templates/orderstable.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<table class="features-table">
<tr>
    <th>Item to buy</th>
    <th>Whom</th>
    <th>Paid in BYN</th>
    <th>Paid in BYR</th>
    <th>Comment</th>
</tr>
    {% for order in orders %}
        <tr>
<td class='grey'>{{ order.item }}</td><td class='grey'>{{ order.whom }}</td>
<td class="grey">{{ order.byn }}</td><td class="grey">{{ order.byr }}</td>
<td class="grey">{{ order.comment }}</td>
<td><a href="{% url 'edit' pk=order.id%}">Edit</a></td><td><a href="{% url 'delete' order.id%}">Delete</a></td>
        </tr>
    {% endfor %}
</table>
<p>Summa in BYR: {{byr}}</p>
<p>Summa in BYN: {{byn}}</p>
<p>Itogo in BYN: {{itog}}</p>
    </br>
{% endblock %}